version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      PGDATA: '/var/lib/postgresql/data/pgdata'
    ports:
      - 5432:5432
    volumes:
      - D:/Work/Databases/Kino++:/var/lib/postgresql/data

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - D:/Work/Databases/Kino++/Mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
